package com.neu.domain;
//import java.time.LocalDateTime;
//
public class ShoppingFeedback {
//    private Integer id;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column litemall_feedback.user_id
//     *
//     * @mbg.generated
//     */
//    private Integer userId;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column litemall_feedback.username
//     *
//     * @mbg.generated
//     */
//    private String username;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column litemall_feedback.mobile
//     *
//     * @mbg.generated
//     */
//    private String mobile;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column litemall_feedback.feed_type
//     *
//     * @mbg.generated
//     */
//    private String feedType;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column litemall_feedback.content
//     *
//     * @mbg.generated
//     */
//    private String content;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column litemall_feedback.status
//     *
//     * @mbg.generated
//     */
//    private Integer status;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column litemall_feedback.has_picture
//     *
//     * @mbg.generated
//     */
//    private Boolean hasPicture;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column litemall_feedback.pic_urls
//     *
//     * @mbg.generated
//     */
//    private String[] picUrls;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column litemall_feedback.add_time
//     *
//     * @mbg.generated
//     */
//    private LocalDateTime addTime;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column litemall_feedback.update_time
//     *
//     * @mbg.generated
//     */
//    private LocalDateTime updateTime;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column litemall_feedback.deleted
//     *
//     * @mbg.generated
//     */
//    private Boolean deleted;
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column litemall_feedback.id
//     *
//     * @return the value of litemall_feedback.id
//     * @mbg.generated
//     */
//    public Integer getId() {
//        return id;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column litemall_feedback.id
//     *
//     * @param id the value for litemall_feedback.id
//     * @mbg.generated
//     */
//    public void setId(Integer id) {
//        this.id = id;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column litemall_feedback.user_id
//     *
//     * @return the value of litemall_feedback.user_id
//     * @mbg.generated
//     */
//    public Integer getUserId() {
//        return userId;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column litemall_feedback.user_id
//     *
//     * @param userId the value for litemall_feedback.user_id
//     * @mbg.generated
//     */
//    public void setUserId(Integer userId) {
//        this.userId = userId;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column litemall_feedback.username
//     *
//     * @return the value of litemall_feedback.username
//     * @mbg.generated
//     */
//    public String getUsername() {
//        return username;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column litemall_feedback.username
//     *
//     * @param username the value for litemall_feedback.username
//     * @mbg.generated
//     */
//    public void setUsername(String username) {
//        this.username = username;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column litemall_feedback.mobile
//     *
//     * @return the value of litemall_feedback.mobile
//     * @mbg.generated
//     */
//    public String getMobile() {
//        return mobile;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column litemall_feedback.mobile
//     *
//     * @param mobile the value for litemall_feedback.mobile
//     * @mbg.generated
//     */
//    public void setMobile(String mobile) {
//        this.mobile = mobile;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column litemall_feedback.feed_type
//     *
//     * @return the value of litemall_feedback.feed_type
//     * @mbg.generated
//     */
//    public String getFeedType() {
//        return feedType;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column litemall_feedback.feed_type
//     *
//     * @param feedType the value for litemall_feedback.feed_type
//     * @mbg.generated
//     */
//    public void setFeedType(String feedType) {
//        this.feedType = feedType;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column litemall_feedback.content
//     *
//     * @return the value of litemall_feedback.content
//     * @mbg.generated
//     */
//    public String getContent() {
//        return content;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column litemall_feedback.content
//     *
//     * @param content the value for litemall_feedback.content
//     * @mbg.generated
//     */
//    public void setContent(String content) {
//        this.content = content;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column litemall_feedback.status
//     *
//     * @return the value of litemall_feedback.status
//     * @mbg.generated
//     */
//    public Integer getStatus() {
//        return status;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column litemall_feedback.status
//     *
//     * @param status the value for litemall_feedback.status
//     * @mbg.generated
//     */
//    public void setStatus(Integer status) {
//        this.status = status;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column litemall_feedback.has_picture
//     *
//     * @return the value of litemall_feedback.has_picture
//     * @mbg.generated
//     */
//    public Boolean getHasPicture() {
//        return hasPicture;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column litemall_feedback.has_picture
//     *
//     * @param hasPicture the value for litemall_feedback.has_picture
//     * @mbg.generated
//     */
//    public void setHasPicture(Boolean hasPicture) {
//        this.hasPicture = hasPicture;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column litemall_feedback.pic_urls
//     *
//     * @return the value of litemall_feedback.pic_urls
//     * @mbg.generated
//     */
//    public String[] getPicUrls() {
//        return picUrls;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column litemall_feedback.pic_urls
//     *
//     * @param picUrls the value for litemall_feedback.pic_urls
//     * @mbg.generated
//     */
//    public void setPicUrls(String[] picUrls) {
//        this.picUrls = picUrls;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column litemall_feedback.add_time
//     *
//     * @return the value of litemall_feedback.add_time
//     * @mbg.generated
//     */
//    public LocalDateTime getAddTime() {
//        return addTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column litemall_feedback.add_time
//     *
//     * @param addTime the value for litemall_feedback.add_time
//     * @mbg.generated
//     */
//    public void setAddTime(LocalDateTime addTime) {
//        this.addTime = addTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column litemall_feedback.update_time
//     *
//     * @return the value of litemall_feedback.update_time
//     * @mbg.generated
//     */
//    public LocalDateTime getUpdateTime() {
//        return updateTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column litemall_feedback.update_time
//     *
//     * @param updateTime the value for litemall_feedback.update_time
//     * @mbg.generated
//     */
//    public void setUpdateTime(LocalDateTime updateTime) {
//        this.updateTime = updateTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table litemall_feedback
//     *
//     * @mbg.generated
//     */
//    public void andLogicalDeleted(boolean deleted) {
//        setDeleted(deleted ? ShoppingAd.Deleted.IS_DELETED.value() : ShoppingAd.Deleted.NOT_DELETED.value());
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column litemall_feedback.deleted
//     *
//     * @return the value of litemall_feedback.deleted
//     * @mbg.generated
//     */
//    public Boolean getDeleted() {
//        return deleted;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column litemall_feedback.deleted
//     *
//     * @param deleted the value for litemall_feedback.deleted
//     * @mbg.generated
//     */
//    public void setDeleted(Boolean deleted) {
//        this.deleted = deleted;
    }
//}