package com.neu.dao;

import com.neu.domain.ShoppingAdmin;
import com.neu.domain.ShoppingAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

/**
 * 管理员操作
 * @author dell
 *
 */
@Repository
public interface ShoppingAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_admin
     *
     * @mbg.generated
     */
    long countByExample(ShoppingAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_admin
     *
     * @mbg.generated
     */
    int deleteByExample(ShoppingAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_admin
     *
     * @mbg.generated
     */
    int insert(ShoppingAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_admin
     *
     * @mbg.generated
     */
    int insertSelective(ShoppingAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_admin
     *
     * @mbg.generated
     */
    ShoppingAdmin selectOneByExample(ShoppingAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_admin
     *
     * @mbg.generated
     */
    ShoppingAdmin selectOneByExampleSelective(@Param("example") ShoppingAdminExample example, @Param("selective") ShoppingAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_admin
     *
     * @mbg.generated
     */
    List<ShoppingAdmin> selectByExampleSelective(@Param("example") ShoppingAdminExample example, @Param("selective") ShoppingAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_admin
     *
     * @mbg.generated
     */
    List<ShoppingAdmin> selectByExample(ShoppingAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_admin
     *
     * @mbg.generated
     */
    ShoppingAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShoppingAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_admin
     *
     * @mbg.generated
     */
    ShoppingAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_admin
     *
     * @mbg.generated
     */
    ShoppingAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShoppingAdmin record, @Param("example") ShoppingAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShoppingAdmin record, @Param("example") ShoppingAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShoppingAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShoppingAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ShoppingAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}