package com.neu.dao;

import com.neu.domain.ShoppingRole;
import com.neu.domain.ShoppingRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

/**
 * 角色
 * @author dell
 *
 */
@Repository
public interface ShoppingRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_role
     *
     * @mbg.generated
     */
    long countByExample(ShoppingRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_role
     *
     * @mbg.generated
     */
    int deleteByExample(ShoppingRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_role
     *
     * @mbg.generated
     */
    int insert(ShoppingRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_role
     *
     * @mbg.generated
     */
    int insertSelective(ShoppingRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_role
     *
     * @mbg.generated
     */
    ShoppingRole selectOneByExample(ShoppingRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_role
     *
     * @mbg.generated
     */
    ShoppingRole selectOneByExampleSelective(@Param("example") ShoppingRoleExample example, @Param("selective") ShoppingRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_role
     *
     * @mbg.generated
     */
    List<ShoppingRole> selectByExampleSelective(@Param("example") ShoppingRoleExample example, @Param("selective") ShoppingRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_role
     *
     * @mbg.generated
     */
    List<ShoppingRole> selectByExample(ShoppingRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_role
     *
     * @mbg.generated
     */
    ShoppingRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShoppingRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_role
     *
     * @mbg.generated
     */
    ShoppingRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_role
     *
     * @mbg.generated
     */
    ShoppingRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShoppingRole record, @Param("example") ShoppingRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShoppingRole record, @Param("example") ShoppingRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShoppingRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShoppingRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ShoppingRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}