package com.neu.dao;

import com.neu.domain.ShoppingUser;
import com.neu.domain.ShoppingUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

/**
 * 用户
 * @author dell
 *
 */
@Repository
public interface ShoppingUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_user
     *
     * @mbg.generated
     */
    long countByExample(ShoppingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_user
     *
     * @mbg.generated
     */
    int deleteByExample(ShoppingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_user
     *
     * @mbg.generated
     */
    int insert(ShoppingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_user
     *
     * @mbg.generated
     */
    int insertSelective(ShoppingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_user
     *
     * @mbg.generated
     */
    ShoppingUser selectOneByExample(ShoppingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_user
     *
     * @mbg.generated
     */
    ShoppingUser selectOneByExampleSelective(@Param("example") ShoppingUserExample example, @Param("selective") ShoppingUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_user
     *
     * @mbg.generated
     */
    List<ShoppingUser> selectByExampleSelective(@Param("example") ShoppingUserExample example, @Param("selective") ShoppingUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_user
     *
     * @mbg.generated
     */
    List<ShoppingUser> selectByExample(ShoppingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_user
     *
     * @mbg.generated
     */
    ShoppingUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShoppingUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_user
     *
     * @mbg.generated
     */
    ShoppingUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_user
     *
     * @mbg.generated
     */
    ShoppingUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShoppingUser record, @Param("example") ShoppingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShoppingUser record, @Param("example") ShoppingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShoppingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShoppingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ShoppingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}