package com.neu.dao;

import com.neu.domain.ShoppingStorage;
import com.neu.domain.ShoppingStorageExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

/**
 * 对象存储
 * @author dell
 *
 */
@Repository
public interface ShoppingStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_storage
     *
     * @mbg.generated
     */
    long countByExample(ShoppingStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_storage
     *
     * @mbg.generated
     */
    int deleteByExample(ShoppingStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_storage
     *
     * @mbg.generated
     */
    int insert(ShoppingStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_storage
     *
     * @mbg.generated
     */
    int insertSelective(ShoppingStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_storage
     *
     * @mbg.generated
     */
    ShoppingStorage selectOneByExample(ShoppingStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_storage
     *
     * @mbg.generated
     */
    ShoppingStorage selectOneByExampleSelective(@Param("example") ShoppingStorageExample example, @Param("selective") ShoppingStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_storage
     *
     * @mbg.generated
     */
    List<ShoppingStorage> selectByExampleSelective(@Param("example") ShoppingStorageExample example, @Param("selective") ShoppingStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_storage
     *
     * @mbg.generated
     */
    List<ShoppingStorage> selectByExample(ShoppingStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_storage
     *
     * @mbg.generated
     */
    ShoppingStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShoppingStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_storage
     *
     * @mbg.generated
     */
    ShoppingStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_storage
     *
     * @mbg.generated
     */
    ShoppingStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShoppingStorage record, @Param("example") ShoppingStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShoppingStorage record, @Param("example") ShoppingStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShoppingStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShoppingStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ShoppingStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}