package com.neu.dao;

import com.neu.domain.ShoppingPermission;
import com.neu.domain.ShoppingPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

/**
 * 管理员权限
 * @author dell
 *
 */
@Repository
public interface ShoppingPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_permission
     *
     * @mbg.generated
     */
    long countByExample(ShoppingPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_permission
     *
     * @mbg.generated
     */
    int deleteByExample(ShoppingPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_permission
     *
     * @mbg.generated
     */
    int insert(ShoppingPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_permission
     *
     * @mbg.generated
     */
    int insertSelective(ShoppingPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_permission
     *
     * @mbg.generated
     */
    ShoppingPermission selectOneByExample(ShoppingPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_permission
     *
     * @mbg.generated
     */
    ShoppingPermission selectOneByExampleSelective(@Param("example") ShoppingPermissionExample example, @Param("selective") ShoppingPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_permission
     *
     * @mbg.generated
     */
    List<ShoppingPermission> selectByExampleSelective(@Param("example") ShoppingPermissionExample example, @Param("selective") ShoppingPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_permission
     *
     * @mbg.generated
     */
    List<ShoppingPermission> selectByExample(ShoppingPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_permission
     *
     * @mbg.generated
     */
    ShoppingPermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShoppingPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_permission
     *
     * @mbg.generated
     */
    ShoppingPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_permission
     *
     * @mbg.generated
     */
    ShoppingPermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShoppingPermission record, @Param("example") ShoppingPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShoppingPermission record, @Param("example") ShoppingPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShoppingPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShoppingPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ShoppingPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}